[package]
name = "utilities"
version = "0.1.0"
edition = "2021"
publish = false

[dependencies]
log = "0.4"
simple_logger = "5.0"
envconfig = "0.10"
strum = { version = "0.26", features = ["derive"]}
